### ISSUE TITLE
Bug with transfer when trimming fat

### ISSUE THREAD

**Issue by jgg16** [disdain13/PokeRoadie#168]
Hi, I got the following settings but it seemed that the rules not being followed. I'm using the 2015.9.5 version.

  (TransferPokemon)true(/TransferPokemon)
  (TransferPriorityType)V(/TransferPriorityType)
  (TransferPriorityType2)IV(/TransferPriorityType2)
  (KeepDuplicateAmount)7(/KeepDuplicateAmount)
  (KeepAboveCP)1000(/KeepAboveCP)
  (KeepAboveIV)86(/KeepAboveIV)
  (KeepAboveV)240(/KeepAboveV)
  (KeepAboveLV)0(/KeepAboveLV)
  (AlwaysTransferBelowCp)0(/AlwaysTransferBelowCp)
  (AlwaysTransferBelowIV)0(/AlwaysTransferBelowIV)
  (AlwaysTransferBelowLV)0(/AlwaysTransferBelowLV)
  (AlwaysTransferBelowV)0(/AlwaysTransferBelowV)
  (TransferTrimFatCount)188(/TransferTrimFatCount)
  (NotTransferPokemonsThatCanEvolve)false(/NotTransferPokemonsThatCanEvolve)

[00:11:01] Pokemon inventory full, trimming the fat...
[00:11:01] Found 188 pokemon to transfer:
[00:11:02] Magnemite (**238V**-481Cp-**78.55%**-Lv20-38Hp) | Candy: 289 | Best Magnemite (**214V**-448Cp-**71.90%**-Lv19-37Hp) 
[00:11:25] Rattata (**234V**-254Cp-**85.71%**-Lv16-39Hp) | Candy: 300 | Best Rattata (**229V**-306Cp-**73.45%**-Lv20-42Hp) 
**[00:11:46] Vaporeon (233V-1337Cp-83.97%-Lv17-151Hp) | Candy: 20 | Best NONE** 
[00:12:25] Rattata (**229V**-306Cp-**73.45%**-Lv20-42Hp) | Candy: 301 | Best Rattata (**199V**-197Cp-**70.64%**-Lv13-36Hp)

**Comment by disdain13** [comment]
Transfer trim fat does not follow standard transfer rules. If it did, then it would never transfer anything. The only reason a bot will ever hit "transfer trim fat" is because your normal transfer rules are too lenient, keeping more than your inventory allows. It is a fallback when you are keeping too much. If inventory fills, it transfers the lowest X based on transfer priority (x being the number specified in TransferTrimFatCount). This number should be set to 5 or 10, maybe even 20... but 188 seems excessive.
