### ISSUE TITLE
InvalidResponseException' was thrown

### ISSUE THREAD

**Issue by sigitpadi** [disdain13/PokeRoadie#19]
[20:08:20] Unhandled exception encountered: Exception of type 'PokemonGo.RocketA
PI.Exceptions.InvalidResponseException' was thrown..

What is it ? Get an error an restarting

**Comment by disdain13** [comment]
This is related to how many consecutive requests you send at a time, and is part of their new measures to persuade us...8) There is currently a randomized delay betwen request 200-300ms. However, I will be making that configurable to allow for tweaking. This same error happens when their servers are having issues, because it starts dropping requests. I don't think we will ever get rid of it completely, but I will work on it some more.  It should just restart and do fine, let me know if it is looping badly.

**Comment by sigitpadi** [comment]
Okay mate. Thanks for your awesome job's :) . I'll be waiting for the next update

**Comment by disdain13** [comment]
@sigitpadi - new release is up!
