### ISSUE TITLE
Transfer/Trim fat issue

### ISSUE THREAD

**Issue by Famey** [disdain13/PokeRoadie#55]
The "TransferTrimFatCount" ignores other settings like "KeepDuplicateAmount" or "KeepAboveIV". I am not sure, if the bot does so on purpose, but I would consider this a bug.

Otherwise, this is a fantastic bot and I appreciate your work a lot.

**Comment by disdain13** [comment]
TransferTrimFat feature does follow those rules intentionally, because it would then be useless. This method is a last resort when you hit the inventory limit. This only happens when your current settings like "KeepDuplicateAmount" or "KeepAboveIV" are too lenient, and you are keeping too many pokemon. If it followed the same rules, it would not transfer anything, because that is how your inventory got filled to begin with.
