### ISSUE TITLE
2-step auth "fix"

### ISSUE THREAD

**Issue by Halt-I-m-Reptar** [disdain13/PokeRoadie#6]
If we could manually add the Refresh Token to the config file, it side-steps the 2-step auth issue for the time being.

**Comment by disdain13** [comment]
For Google Login - Email and Password are now REQUIRED(because we need now GPSO for Login). 
Two step auth does not work:
You will receive this error message: [17:21:04] NeedsBrowser from Pokemon Go Rocket API
If you do NOT want to disable your two-factor auth, please visit the following link and setup an app password. This is the only way of using the bot without disabling two-factor auth: https://security.google.com/settings/security/apppasswords
